const TODAY = new Date('2026-05-07T00:00:00-07:00');

const FREE_BETA = true;

const SCHOLARSHIP_SEEDS = [
  seed('community-scholarship','Community Scholarship','Sacramento Region Community Foundation',['Sacramento County'],'2026-03-13','Verified 2026 deadline: March 13, 2026','https://sacregcf.academicworks.com/opportunities/1973',['Graduating high school senior from a Sacramento County high school','Plan to attend a 2-year or 4-year college/university, vocational or trade school','Minimum 2.5 unweighted GPA; preference for 2.5–3.5','Additional eligibility may apply according to the official portal','Preference for first-generation college students'],['General application','Additional official-portal eligibility information if required','Two essays','One non-family reference letter'],['Describe a time you contributed to your school, neighborhood, or a Sacramento-area organization. What did you learn, and how did it shape your goals?','Tell us something about your background, identity, challenges, growth, gratitude, or lived experience that the Foundation should understand.'],['sacramento','community service','leadership','need','first-gen','local'],12,'high','$2,500 per year for up to 4 years','Local Community Scholarship','Verified from official AcademicWorks page on 2026-05-07.'),
  seed('li-family-charitable-foundation','Li Family Charitable Foundation Scholarship','Sacramento Region Community Foundation',['Sacramento County','Placer County','Yolo County'],'2026-03-13','Verified 2026 deadline: March 13, 2026','https://sacregcf.academicworks.com/opportunities/1959',['Plan to attend a 4-year college/university','Minimum 3.0 GPA','Preferred: high school senior or undergraduate who attended school in Sacramento, Yolo, or Placer County','Preferred: first-generation or disadvantaged youth context'],['General application','Essay about a hardship and how the scholarship helps educational goals','Reference letter','Additional official-portal eligibility information if required'],['Write about one hardship you encountered and how you overcame it. How would this scholarship help you achieve your educational dreams?'],['sacramento','placer','yolo','need','first-gen','culture','leadership'],11,'high','$3,000','Need / First-Generation Scholarship','Verified from official AcademicWorks page on 2026-05-07.'),
  seed('sacramento-reach','Sacramento Region REACH Scholarship','Sacramento Region Community Foundation',['Sacramento County','Placer County','Yolo County','El Dorado County'],'2026-04-06','Verified 2026 deadline: April 6, 2026','https://sacregcf.academicworks.com/opportunities/1836',['Environmental sciences, land use planning, natural resources, cultural resources, or sustainability major/course of study','Attended or attending high school or college in El Dorado, Placer, Sacramento, or Yolo County','Minimum 3.0 unweighted GPA','Additional official-portal eligibility status if requested'],['General application','100–250 word environmental career essay','Reference letter'],['Describe why you are pursuing or plan to pursue an environmental field and what you have done or plan to do to prepare.'],['sacramento','placer','yolo','environment','stem','career','first-gen','need'],11,'high','$1,500; renewable up to 4 years','Environmental / Sustainability Scholarship','Verified from official AcademicWorks page on 2026-05-07.'),
  seed('jack-ellie-matranga','Jack and Ellie Matranga Scholarship','Sacramento Region Community Foundation',['Sacramento County','Placer County','Yolo County','El Dorado County'],'2026-03-13','Verified 2026 deadline: March 13, 2026','https://sacregcf.academicworks.com/opportunities/1963',['High school senior attending a school in El Dorado, Placer, Sacramento, or Yolo County','Pursuing mass media such as communications, journalism, public relations, advertising, or graphic design','Minimum 3.0 unweighted GPA','Additional official-portal eligibility status if requested'],['General application','Personal statement on mass media education/career goals','Reference letter'],['Provide a personal statement about your educational and career goals in mass media.'],['sacramento','placer','yolo','media','communications','career','need'],12,'high','$2,000–$3,000','Mass Media Scholarship','Verified from official AcademicWorks page on 2026-05-07.'),
  seed('lionakis-foundation','Lionakis Foundation Scholarship Program','Sacramento Region Community Foundation',['California','Sacramento County','Placer County'],'2026-03-13','Verified 2026 deadline: March 13, 2026','https://sacregcf.academicworks.com/opportunities/1882',['Architecture, engineering, or interior design major/course of study','High school senior or undergraduate planning to attend a 2-year or 4-year college/university','Minimum 2.5 unweighted GPA','Additional official-portal eligibility status if requested'],['General application','Career-goals essay','Reference letter'],['Provide a personal statement on your educational and career goals in architecture, engineering, or interior design.'],['architecture','engineering','stem','career','need','california'],11,'high','$2,500; renewable up to 3 years','Architecture / Engineering Scholarship','Verified from official AcademicWorks page on 2026-05-07.'),
  seed('aia-central-valley','AIA Central Valley / John Ellis Architectural Scholarship','Sacramento Region Community Foundation',['Sacramento County','Placer County','Yolo County','El Dorado County','California'],'2026-03-13','Verified 2026 deadline: March 13, 2026','https://sacregcf.academicworks.com/opportunities/1937',['High school senior, undergraduate, graduate, or adult re-entry student','Majoring in architecture at a community college or four-year college/university','Minimum 3.5 GPA','Attended or currently attending school in listed Northern/Central California counties including Sacramento, Placer, Yolo, and El Dorado','Full-time enrollment'],['Architecture eligibility questions','Essay about life/family inspiration for studying architecture','Two recommendation letters'],['What in your family or life story has influenced or inspired you to study architecture?'],['architecture','design','career','placer','sacramento','yolo'],12,'high','$1,000','Architecture Scholarship','Verified from official AcademicWorks page on 2026-05-07.'),
  seed('dreier-family','Dreier Family Scholarship','Sacramento Region Community Foundation',['Sacramento County'],'2026-03-13','Verified 2026 deadline: March 13, 2026','https://sacregcf.academicworks.com/opportunities/1932',['High school senior or undergraduate currently attending school in Sacramento County','Planning to attend a 2-year college, vocational, trade, or technical school in Sacramento County','Minimum 2.5 cumulative GPA','Additional eligibility context','Plan to work at least 10 hours/week while attending college'],['General application','Educational/career goals essay','One recommendation letter'],['What are your educational and career goals, and where do you see yourself in 5–10 years?'],['sacramento','career','trade','community college','need','work','foster youth'],12,'high','$1,000–$3,000','Career / Trade Scholarship','Verified from official AcademicWorks page on 2026-05-07.'),
  seed('benny-goodman','Benny Goodman Foundation Scholarship','Sacramento Region Community Foundation',['California','Sacramento County','Placer County'],'2026-03-13','Verified 2026 deadline: March 13, 2026','https://sacregcf.academicworks.com/opportunities/1889',['Attending any University of California or California State University in the fall','3.0 GPA in music classes','Majoring in music with emphasis in jazz or classical; preference for clarinet','Plan to pursue a career in music'],['Activity/work/performance list','Two recommendations, one from music director/instructor','Essay under 500 words'],['How has music played a role in your life, and what are your future goals in music?'],['music','arts','career','california','leadership'],12,'high','$1,000–$3,500','Music Scholarship','Verified from official AcademicWorks page on 2026-05-07.'),
  seed('david-breaux','David Breaux Memorial Scholarship','Sacramento Region Community Foundation',['Yolo County','Sacramento County'],'2026-03-13','Verified 2026 deadline: March 13, 2026','https://sacregcf.academicworks.com/opportunities/1903',['High school senior or undergraduate in first year of study planning for a 2-year or 4-year college/university','Attended or currently attending school in Yolo County','Minimum 3.0 GPA','Additional official-portal eligibility status if requested'],['General application','Essay on social justice and compassion','Two reference letters'],['Describe your view on social justice and compassion and how it has or may play a role in your life.'],['yolo','social justice','community service','leadership','need'],11,'high','$2,000; renewable up to 1 year','Social Justice Scholarship','Verified from official AcademicWorks page on 2026-05-07.'),
  seed('dillard-jackson','Dillard-Jackson Family Scholarship','Sacramento Region Community Foundation',['Sacramento County'],'2026-03-13','Verified 2026 deadline: March 13, 2026','https://sacregcf.academicworks.com/opportunities/1935',['Graduating senior from a high school in the Elk Grove school district','Planning to major in agriculture at a 2-year community college, 4-year college, or university','Minimum 3.0 GPA','Additional eligibility context','Full-time enrollment'],['General application','Agriculture goals essay','Reference letter from teacher or agriculture/community contact'],['Why are you majoring in agriculture, and what are your career goals?'],['sacramento','elk grove','agriculture','career','need'],12,'high','$1,000','Agriculture Scholarship','Verified from official AcademicWorks page on 2026-05-07.'),
  seed('sacramento-police-foundation','Sacramento Police Foundation Scholarship','Sacramento Region Community Foundation',['Sacramento County'],'2026-05-01','Verified 2026 deadline: May 1, 2026','https://sacregcf.academicworks.com/opportunities/1955',['High school senior enrolled in a Criminal Justice and Public Service Magnet Academy program','Plan to attend a 2-year or 4-year college/university or vocational/trade school','Minimum 2.5 unweighted GPA','Plan to complete 50 volunteer service hours by May 15, 2026'],['General application','Volunteer hours documentation or completion plan','Essay on career goals and Magnet Academy impact','Reference letter'],['Address your educational/career goals and how the Magnet Academy impacted your decisions and growth.'],['sacramento','public service','criminal justice','community service','career'],12,'high','$1,000','Public Service Scholarship','Verified from official AcademicWorks page on 2026-05-07.'),
  seed('nancy-reardan','Nancy B. Reardan Scholarship Fund','Sacramento Region Community Foundation',['Sacramento County'],'2025-03-14','Official page currently shows last verified deadline: March 14, 2025; annual cycle — verify before applying','https://sacregcf.academicworks.com/opportunities/1721',['Female high school senior attending a school in Sacramento County, or renewal student who attended Sacramento County high school','Plan to attend a two-year college, four-year college/university, vocational or trade school','Minimum 3.5 GPA','Additional eligibility context','Preference for current or former foster youth'],['Personal essay','Eligibility questions','Two reference letters'],['Describe your educational and career goals.'],['sacramento','women','foster youth','need','leadership'],12,'high','$2,000–$4,000','Women / Foster Youth Scholarship','Official page fetched 2026-05-07; deadline shown is 2025, so app labels it as annual/needs fresh verification before applying.')
];

const PACKET_TEMPLATES = {
  fullPacket: ['Overview', 'Fit rationale', 'Deadline verification', 'Eligibility checklist', 'Required documents', 'Essay prompt breakdown', 'Starter draft/outline', 'Recommendation guidance', 'Application steps', 'Submission checklist', 'Timeline'],
  lightSummary: ['What it is', 'Deadline', 'Eligibility', 'Requirements', 'How to approach'],
  essayStarter: ['Hook: concrete student story', 'Proof: activity/work/service example', 'Bridge: connect proof to scholarship values', 'Goal: major/career plan', 'Close: gratitude + local impact'],
  recommendationRequest: ['Ask 3-4 weeks before deadline', 'Give recommender resume + prompt + deadline', 'Share 2-3 traits to emphasize', 'Send polite reminder 7 days before due date'],
  applicationChecklist: ['Verify deadline on official page', 'Create account only on official scholarship site', 'Draft essays in a separate doc', 'Request recommendation', 'Review for accuracy', 'Submit before deadline', 'Save confirmation'],
  faq: ['Free local beta', 'No award guarantees', 'Deadlines must be verified on official pages', 'Submit applications only through official scholarship portals', 'Students under 18 are welcome; reviewing with a parent or guardian is encouraged'],
  confirmationEmail: ['Subject: Your scholarship starter pack is ready', 'Confirm the starter pack is ready', 'Remind the family to verify the official deadline and eligibility', 'Keep the language simple and reassuring'],
  waitlistEmail: ['Subject: We saved your scholarship matches', 'Confirm the matches are saved', 'Invite them to return and refine the free beta matches', 'Keep the message short and supportive'],
  rejectionEmail: ['Subject: We could not confirm a strong match', 'State that the profile or current-cycle source set was not strong enough', 'Invite them to update the information and try again', 'Keep the tone respectful and direct'],
  adminReviewWorkflow: ['Intake comes in', 'Verify completeness', 'Run discovery/ranking', 'Check deadline and eligibility notes', 'Review the best-match packet', 'Smoke test the page', 'Launch only after owner review']
};

const SAMPLE_STUDENT = { studentName:'Maya Alvarez', parentEmail:'maya.parent@example.test', studentAge:'17', grade:'12', gpa:'3.5-3.9', county:'Sacramento County', zip:'95819', school:'East Sacramento High School', activities:'Saturday food bank volunteer, founder of a peer tutoring circle, part-time barista, first chair clarinet, and senior class service chair', priorityThemes:'service, first-gen, local', majorCareer:'public health with a long-term goal of working in community clinics' };

function seed(id,name,provider,region,deadline,deadlineLabel,link,eligibility,requirements,essayPrompts,tags,minGrade,quality,awardRange,previewCategory,sourceNotes='Verified from the official scholarship page.'){ return { id,name,provider,region,deadline,deadlineLabel,link,eligibility,requirements,essayPrompts,tags,minGrade,quality,awardRange,previewCategory,sourceNotes }; }
function normalizeText(value) { return String(value || '').trim(); }
function splitTags(value) { return normalizeText(value).toLowerCase().split(/[,;\n]+|\s+and\s+/).map(s => s.trim()).filter(Boolean); }
function gradeNumber(grade) { const g = normalizeText(grade).toLowerCase(); if (g.includes('gap') || g.includes('recent graduate') || g.includes('12') || g.includes('senior')) return 12; if (g.includes('11') || g.includes('junior')) return 11; if (g.includes('10')) return 10; if (g.includes('9')) return 9; return 11; }
function isExpiredLowQuality(scholarship, today = TODAY) { const deadline = new Date(`${scholarship.deadline}T23:59:59-07:00`); const keepForPlanning = /annual|verify|historically|typical|verified 2026/i.test(scholarship.deadlineLabel || ''); return scholarship.quality === 'low' || (!keepForPlanning && deadline < today); }
function regionScore(student, scholarship) { const loc = `${student.county || ''} ${student.zip || ''} ${student.location || ''}`.toLowerCase(); return scholarship.region.some(r => loc.includes(r.toLowerCase().replace(' county',''))) ? 4 : scholarship.region.includes('California') ? 2 : 0; }
function scoreScholarship(student, scholarship) {
  if (isExpiredLowQuality(scholarship) || gradeNumber(student.grade) < scholarship.minGrade) return -999;
  const studentTags = [...splitTags(student.activities), ...splitTags(student.interests), ...splitTags(student.priorityThemes), ...splitTags(student.majorCareer), ...splitTags(student.qualifiers), normalizeText(student.county).toLowerCase().replace(' county','')];
  let score = regionScore(student, scholarship);
  for (const tag of scholarship.tags) if (studentTags.some(t => tag.includes(t) || t.includes(tag))) score += 3;
  if (/service|volunteer|community|tutor|food bank/i.test(student.activities || '') && scholarship.tags.includes('community service')) score += 4;
  if (/leader|captain|president|mentor|chair|founder/i.test(student.activities || '') && scholarship.tags.includes('leadership')) score += 3;
  if (/engineer|construction|transport|stem|computer|architecture|health|public|nursing|business|media|music|agriculture|justice/i.test(student.majorCareer || '') && scholarship.tags.some(t => ['engineering','architecture','stem','career','media','music','agriculture','public service','criminal justice'].includes(t))) score += 3;
  if (/first.gen|first generation/i.test(student.qualifiers || '') && scholarship.tags.includes('first-gen')) score += 3;
  if (/need|aid/i.test(student.qualifiers || '') && scholarship.tags.includes('need')) score += 2;
  return score;
}
function discoverScholarships(student, seeds = SCHOLARSHIP_SEEDS) { const ranked = seeds.map(s => ({ ...s, fitScore: scoreScholarship(student, s) })).filter(s => s.fitScore > -999).sort((a,b) => b.fitScore - a.fitScore || a.name.localeCompare(b.name)); return { best: ranked[0] || null, lightMatches: ranked.slice(1, 3), additionalMatches: ranked.slice(3), lockedMatches: [], totalFound: ranked.length, ranked }; }
function listStudentSignals(student) {
  const signals = [];
  const activities = normalizeText(student.activities);
  const career = normalizeText(student.majorCareer);
  const qualifiers = normalizeText(student.qualifiers);
  if (activities) signals.push(`your ${activities.split(',')[0].trim()} experience`);
  if (/tutor|mentor|teach/i.test(activities)) signals.push('the tutoring or mentoring work you can describe with specifics');
  if (/job|work|barista|cashier|caregiv|family/i.test(activities)) signals.push('the responsibility you carry outside school');
  if (/president|chair|captain|leader|founder/i.test(activities)) signals.push('a leadership role with visible follow-through');
  if (career) signals.push(`your ${career} goal`);
  if (/first.gen|first generation/i.test(qualifiers)) signals.push('your first-generation college context, if you choose to share it');
  return [...new Set(signals)].slice(0, 4);
}
function buildFitRationale(student, scholarship) {
  const name = normalizeText(student.studentName) || 'This student';
  const reasons = [];
  const signals = listStudentSignals(student);
  if (regionScore(student, scholarship) >= 4) reasons.push(`${name} has a real local tie through ${normalizeText(student.county) || 'the Sacramento/Placer area'}`);
  if (/service|volunteer|community|tutor|food bank/i.test(student.activities || '') && scholarship.tags.includes('community service')) reasons.push(`the application can point to ${signals.find(s => /volunteer|tutor|food bank|experience|work/i.test(s)) || 'specific service work'} instead of generic language`);
  if (/leader|captain|president|mentor|chair|founder/i.test(student.activities || '') && scholarship.tags.includes('leadership')) reasons.push('there is a concrete leadership example to use in essays and recommendation requests');
  if (/first.gen|first generation/i.test(student.qualifiers || '') && scholarship.tags.includes('first-gen')) reasons.push('the first-generation angle may strengthen the story where the application invites it');
  if (/need|aid/i.test(student.qualifiers || '') && scholarship.tags.includes('need')) reasons.push('aid-related context may matter if the official application asks for it');
  if (signals.length && reasons.length < 3) reasons.push(`the profile already has usable details: ${signals.join('; ')}`);
  return reasons.length ? `This is a strong first target because ${reasons.join(', ')}.` : `This is a practical target because ${name}'s profile has clear material for a specific application.`;
}
function makeEssayOutline(student) {
  const name = normalizeText(student.studentName) || 'the student';
  const activities = normalizeText(student.activities) || 'one meaningful class, job, family responsibility, club, sport, or volunteer activity';
  const firstActivity = activities.split(',')[0].trim();
  const goal = normalizeText(student.majorCareer) || 'your next education/career step';
  const local = normalizeText(student.county) || 'your local community';
  return [`Opening story: Start with one real scene from ${firstActivity} — what was happening, who needed help, and what ${name} did next.`, `What it shows: Connect that moment to reliability, service, leadership, or persistence without overstating it.`, `Student-specific bridge: Tie the story to ${goal}.`, `Local angle: Mention how studying or living in ${local} shaped the way ${name} thinks about community and opportunity.`, 'Close: Name the practical barrier the scholarship would reduce and the next step the student is ready to take.'];
}
function makeEssayStarter(student, scholarship) { const name = normalizeText(student.studentName) || 'the student'; const activity = (normalizeText(student.activities) || 'one regular responsibility').split(',')[0].trim(); const goal = normalizeText(student.majorCareer) || 'the student’s college and career goal'; const county = normalizeText(student.county) || 'the student’s community'; const prompt = scholarship.essayPrompts?.[0] || 'Tell us about your goals and experiences.'; return `Start with a specific moment from ${activity}, not a broad statement about wanting a scholarship. For this prompt — "${prompt}" — the strongest opening is a short scene that shows ${name}'s follow-through, then a bridge to ${goal} and why ${county} shaped that goal. Keep it honest and concrete: one scene, one lesson, one next step.`; }
function deadlineUrgency(scholarship, today = TODAY) { const deadline = new Date(`${scholarship.deadline}T23:59:59-07:00`); if (!Number.isNaN(deadline.getTime()) && deadline >= today) { const days = Math.max(0, Math.round((deadline - today) / 86400000)); return days === 0 ? 'Deadline today — verify immediately' : `Deadline in ${days} day${days === 1 ? '' : 's'} — verify on the official page`; } if (/verified 2026 deadline/i.test(scholarship.deadlineLabel || '')) return `${scholarship.deadlineLabel} — current cycle appears closed; use for next-cycle planning unless the official portal says otherwise`; return `${scholarship.deadlineLabel || 'Annual cycle — verify on official page'}`; }
function realnessSignal(scholarship) { const tags = scholarship.tags.join(' '); if (/community service|volunteer/i.test(tags)) return 'Strong applications use specific service hours, named impact, and a recommender who can confirm follow-through.'; if (/leadership/i.test(tags)) return 'Strong applications point to real responsibility, not just a title.'; if (/stem|engineering|architecture|career|media|music|agriculture/i.test(tags)) return 'Strong applications connect the student’s course, job, project, or activity to a clear career direction.'; if (/first-gen|need/i.test(tags)) return 'Strong applications explain practical barriers clearly and show how the opportunity helps the student persist.'; return 'Strong applications use clear goals, honest details, complete documents, and verified official deadlines.'; }
function allVisibleMatches(report) { return report.discovery.ranked.map((m, idx) => ({ scholarshipId:m.id, name:m.name, provider:m.provider, awardRange:m.awardRange, deadline:m.deadlineLabel, deadlineUrgency:deadlineUrgency(m), realnessSignal:realnessSignal(m), link:m.link, sourceNotes:m.sourceNotes, fitRationale:buildFitRationale(report.student,m), requirements:m.requirements, eligibility:m.eligibility, priority:idx === 0 ? 'Best Match' : idx < 3 ? 'Strong Match' : 'Additional Match' })); }
function generateReport(student) {
  const normalizedStudent = { ...student, parentEmail: normalizeText(student.parentEmail || student.email).toLowerCase() };
  const discovery = discoverScholarships(normalizedStudent);
  if (!discovery.best) return { student: normalizedStudent, discovery, fullPacket: null, lightMatches: [], additionalMatches: [], allMatches: [], unlocked: true, freeBeta: FREE_BETA, disclaimer: disclaimer() };
  const s = discovery.best;
  const fullPacket = { scholarshipId: s.id, name: s.name, provider: s.provider, overview: `${s.name} is a verified official-source opportunity in this free beta. Use the official link to confirm the portal status before applying.`, fitRationale: buildFitRationale(normalizedStudent, s), deadline: s.deadlineLabel, deadlineUrgency: deadlineUrgency(s), realnessSignal: realnessSignal(s), eligibilityChecklist: s.eligibility.map(x => ({ item: x, status: 'Verify / prepare' })), requiredDocuments: s.requirements, essayPromptBreakdown: s.essayPrompts.map(prompt => ({ prompt, approach: 'Answer with one specific story, one proof point, and one clear education/career goal.' })), starterDraftOutline: makeEssayOutline(normalizedStudent), essayStarter: makeEssayStarter(normalizedStudent, s), recommendationGuidance: PACKET_TEMPLATES.recommendationRequest, applicationInstructions: ['Open the official scholarship link only', 'Verify the portal status and eligibility', 'Draft essays in a separate document', 'Collect documents', 'Ask recommender early', 'Submit before the official deadline if the current cycle is open', 'Save confirmation'], submissionChecklist: PACKET_TEMPLATES.applicationChecklist, timeline: ['Today: verify official page and save deadline/status', 'Next 48 hours: collect transcript/resume/activity list', 'This week: draft essay and request recommendation', '7 days before due date: final review', '2 days before due date: submit and save confirmation'], link: s.link, sourceNotes: s.sourceNotes };
  const lightMatches = discovery.lightMatches.map(m => ({ scholarshipId: m.id, name: m.name, provider: m.provider, overview: `${m.provider} official-source opportunity for ${m.region.join('/')} students.`, deadline: m.deadlineLabel, deadlineUrgency: deadlineUrgency(m), realnessSignal: realnessSignal(m), eligibility: m.eligibility.join('; '), requirements: m.requirements.join('; '), link:m.link, sourceNotes:m.sourceNotes, approachNote: `Use this as a second-pass match. Verify the official portal, then reuse the strongest student story if the prompt fits. Fit score: ${m.fitScore}.` }));
  const report = { student: normalizedStudent, account: createAccountSession(normalizedStudent), discovery, unlocked: true, freeBeta: FREE_BETA, fullPacket, lightMatches, additionalMatches: [], allMatches: [], templates: PACKET_TEMPLATES, disclaimer: disclaimer(), generatedAt: new Date().toISOString() };
  report.allMatches = allVisibleMatches(report);
  report.additionalMatches = report.allMatches.slice(3);
  report.unlockedCount = report.allMatches.length;
  return report;
}
function createAccountSession(student) { const email = normalizeText(student.parentEmail || student.email).toLowerCase(); return { email, accountId: email ? `acct_${hashString(email)}` : `acct_demo_${Date.now()}`, sessionId: `sess_${hashString(`${email}|${Date.now()}`)}`, dashboardPath: '#dashboard', mode: 'free_beta_local_access' }; }
function hashString(value) { let h = 0; for (const ch of String(value)) h = Math.imul(31, h) + ch.charCodeAt(0) | 0; return Math.abs(h).toString(36); }
function scheduleEmailQueue(report, now = new Date()) { const email = report.student.parentEmail; const base = now.getTime(); const mk = (delayHours, subject, purpose, body) => ({ id: `${report.account.accountId}_${delayHours}h`, to: email, subject, purpose, scheduledAt: new Date(base + delayHours*3600*1000).toISOString(), status: 'queued_placeholder_not_sent', body }); return [mk(0, 'Your free scholarship starter pack is ready', 'instant_dashboard_ready', `Hi ${report.student.studentName || 'there'} — your free local beta Starter Pack is ready. Start with the Best Match, then review the remaining verified-source matches. No awards are guaranteed; verify each official deadline before applying.`), mk(24, 'Reminder: verify your top scholarship deadline', '24h_deadline_verification', 'Quick reminder: before drafting, open the official scholarship page and confirm the current portal status, deadline, and eligibility.'), mk(48, 'Next step: choose one essay to draft first', '48h_application_momentum', 'Pick the strongest fit, draft one specific story, and ask a recommender early if the official application requires one.')]; }
function queueAccessAndFollowupEmails(report, storage = null) { const queue = scheduleEmailQueue(report); if (storage?.setItem) storage.setItem('ssp_email_queue', JSON.stringify(queue)); return queue; }
function getPaymentLink() { if (!FREE_BETA && typeof window !== 'undefined' && window.SSP_PAYMENT_LINK) return window.SSP_PAYMENT_LINK; return ''; }
function unlockFullPlan(report) { return { ...report, unlocked: true, unlockedCount: report.discovery.totalFound, unlockedAt: new Date().toISOString(), unlockedOpportunities: allVisibleMatches(report).slice(3) }; }
function upgradeCopy(totalFound) { return { totalOpportunitiesFound: totalFound, paymentMode: FREE_BETA ? 'free_beta_no_payment' : (getPaymentLink() ? 'configured_payment_link' : 'simulated_unlock_no_payment_claim'), primaryCta: 'Free beta: show all verified matches', ctaSubtext: 'All currently matched scholarships are visible in this beta.', plans: [] }; }
function createUpgradeIntent(planId, contactEmail='') { return { planId, planName: 'Free beta', price: '$0', contactEmail, status: 'free_beta_no_payment', paymentLink: '', message: 'This beta is free. No payment is requested or processed.', createdAt: new Date().toISOString() }; }
function disclaimer() { return 'Free beta. We recommend scholarships and help prepare applications. We do not guarantee scholarships, awards, admissions, or outcomes. Always verify deadlines and eligibility on the official scholarship page before applying.'; }
function logAnalyticsEvent(eventName, details = {}, storage = null, now = new Date()) { const allowed = new Set(['intake_completed','report_viewed','dashboard_viewed','print_clicked','beta_refine_clicked','upgrade_clicked','unlock_triggered']); if (!allowed.has(eventName)) throw new Error(`Unknown analytics event: ${eventName}`); const store = storage || (typeof localStorage !== 'undefined' ? localStorage : null); let events = []; if (store?.getItem) { try { events = JSON.parse(store.getItem('ssp_analytics_events') || '[]'); } catch { events = []; } } const event = { eventName, details, at: now.toISOString() }; events.push(event); if (store?.setItem) store.setItem('ssp_analytics_events', JSON.stringify(events)); return event; }
function makeDashboardModel(report, storedStatuses = {}) { const visible = [report.fullPacket, ...(report.lightMatches || []), ...(report.additionalMatches || [])].filter(Boolean); const items = visible.map((item, idx) => ({ id: item.scholarshipId, name: item.name, status: storedStatuses[item.scholarshipId]?.status || 'Not started', priority: idx === 0 ? 'Best Match' : idx < 3 ? 'Strong Match' : 'Additional Match', deadline: item.deadline, deadlineUrgency: item.deadlineUrgency, realnessSignal: item.realnessSignal, nextAction: idx === 0 ? 'Open official page and confirm current-cycle status before drafting.' : 'Confirm official requirements before spending time on the application.', documents: idx === 0 ? report.fullPacket.requiredDocuments : (Array.isArray(item.requirements) ? item.requirements : String(item.requirements || '').split('; ').filter(Boolean)), checklist: ['Open official page', 'Confirm current cycle/deadline', 'Confirm eligibility', 'Collect documents', 'Draft/update essay', 'Request recommendation if needed', 'Submit only on official site', 'Save confirmation'].map(label => ({ label, done: storedStatuses[item.scholarshipId]?.checklist?.includes(label) || false })) })); return { items, totalFound: report.discovery.totalFound, unlockedCount: items.length, progressPercent: items.length ? Math.round(items.flatMap(i=>i.checklist).filter(c=>c.done).length / (items.length*8) * 100) : 0 }; }
function saveLocal(key, value) { if (typeof localStorage !== 'undefined') localStorage.setItem(key, JSON.stringify(value)); return value; }
function loadLocal(key, fallback=null) { if (typeof localStorage === 'undefined') return fallback; try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }

const ScholarshipStarter = { SCHOLARSHIP_SEEDS, PACKET_TEMPLATES, SAMPLE_STUDENT, FREE_BETA, discoverScholarships, generateReport, makeDashboardModel, createUpgradeIntent, createAccountSession, scheduleEmailQueue, queueAccessAndFollowupEmails, unlockFullPlan, logAnalyticsEvent, saveLocal, loadLocal, disclaimer, isExpiredLowQuality, scoreScholarship, deadlineUrgency, realnessSignal };
if (typeof window !== 'undefined') window.ScholarshipStarter = ScholarshipStarter;
export { SCHOLARSHIP_SEEDS, PACKET_TEMPLATES, SAMPLE_STUDENT, FREE_BETA, discoverScholarships, generateReport, makeDashboardModel, createUpgradeIntent, createAccountSession, scheduleEmailQueue, queueAccessAndFollowupEmails, unlockFullPlan, logAnalyticsEvent, deadlineUrgency, realnessSignal, disclaimer, scoreScholarship, isExpiredLowQuality };
