const TODAY = new Date('2026-05-08T00:00:00-07:00');
const FREE_BETA = true;

const STATUS_OPTIONS = ['Not started', 'In progress', 'Submitted', 'Awaiting decision', 'Awarded', 'Not selected'];

function seed(data) {
  return {
    tier: 'A',
    scope: 'Local Sacramento + Placer',
    region: [],
    educationLevel: 'High school senior',
    status: 'Verify before applying',
    quality: 'high',
    amountMin: 0,
    amountMax: 0,
    tags: [],
    requirements: [],
    eligibility: [],
    essayPrompts: [],
    sourceNotes: 'Public scholarship page; verify before applying.',
    ...data
  };
}

const TIER_A_SCHOLARSHIPS = [
  seed({ id:'community-scholarship', name:'Community Scholarship', provider:'Sacramento Region Community Foundation', region:['Sacramento County'], deadline:'2026-03-13', deadlineLabel:'Verified 2026 deadline: March 13, 2026', link:'https://sacregcf.academicworks.com/opportunities/1973', eligibility:['Graduating high school senior from a Sacramento County high school','Plan to attend a 2-year or 4-year college/university, vocational or trade school','Minimum 2.5 unweighted GPA; preference for 2.5-3.5'], requirements:['General application','Two essays','One non-family reference letter'], essayPrompts:['Describe a time you contributed to your school, neighborhood, or a Sacramento-area organization.','Tell us something about your background, identity, challenges, growth, gratitude, or lived experience.'], tags:['sacramento','community service','leadership','need','first-gen','local'], minGrade:12, amount:'$2,500 per year for up to 4 years', amountMin:2500, amountMax:10000, previewCategory:'Local Community Scholarship', sourceNotes:'Verified from official AcademicWorks page on 2026-05-07.' }),
  seed({ id:'li-family-charitable-foundation', name:'Li Family Charitable Foundation Scholarship', provider:'Sacramento Region Community Foundation', region:['Sacramento County','Placer County','Yolo County'], deadline:'2026-03-13', deadlineLabel:'Verified 2026 deadline: March 13, 2026', link:'https://sacregcf.academicworks.com/opportunities/1959', eligibility:['Plan to attend a 4-year college/university','Minimum 3.0 GPA','Preferred: attended school in Sacramento, Yolo, or Placer County','Preferred: first-generation or disadvantaged youth context'], requirements:['General application','Hardship and education-goals essay','Reference letter'], essayPrompts:['Write about one hardship you encountered and how you overcame it.'], tags:['sacramento','placer','yolo','need','first-gen','culture','leadership'], minGrade:11, amount:'$3,000', amountMin:3000, amountMax:3000, previewCategory:'Need / First-Generation Scholarship', sourceNotes:'Verified from official AcademicWorks page on 2026-05-07.' }),
  seed({ id:'sacramento-reach', name:'Sacramento Region REACH Scholarship', provider:'Sacramento Region Community Foundation', region:['Sacramento County','Placer County','Yolo County','El Dorado County'], deadline:'2026-04-06', deadlineLabel:'Verified 2026 deadline: April 6, 2026', link:'https://sacregcf.academicworks.com/opportunities/1836', eligibility:['Environmental sciences, land use planning, natural resources, cultural resources, or sustainability major/course of study','Attended or attending school or college in El Dorado, Placer, Sacramento, or Yolo County','Minimum 3.0 unweighted GPA'], requirements:['General application','100-250 word environmental career essay','Reference letter'], essayPrompts:['Describe why you are pursuing or plan to pursue an environmental field.'], tags:['sacramento','placer','environment','stem','career','first-gen','need'], minGrade:11, amount:'$1,500; renewable up to 4 years', amountMin:1500, amountMax:6000, previewCategory:'Environmental / Sustainability Scholarship', sourceNotes:'Verified from official AcademicWorks page on 2026-05-07.' }),
  seed({ id:'jack-ellie-matranga', name:'Jack and Ellie Matranga Scholarship', provider:'Sacramento Region Community Foundation', region:['Sacramento County','Placer County','Yolo County','El Dorado County'], deadline:'2026-03-13', deadlineLabel:'Verified 2026 deadline: March 13, 2026', link:'https://sacregcf.academicworks.com/opportunities/1963', eligibility:['High school senior attending a school in El Dorado, Placer, Sacramento, or Yolo County','Pursuing mass media such as communications, journalism, public relations, advertising, or graphic design','Minimum 3.0 unweighted GPA'], requirements:['General application','Personal statement on mass media education/career goals','Reference letter'], essayPrompts:['Provide a personal statement about your educational and career goals in mass media.'], tags:['sacramento','placer','media','communications','career'], minGrade:12, amount:'$2,000-$3,000', amountMin:2000, amountMax:3000, previewCategory:'Mass Media Scholarship', sourceNotes:'Verified from official AcademicWorks page on 2026-05-07.' }),
  seed({ id:'lionakis-foundation', name:'Lionakis Foundation Scholarship Program', provider:'Sacramento Region Community Foundation', region:['California','Sacramento County','Placer County'], deadline:'2026-03-13', deadlineLabel:'Verified 2026 deadline: March 13, 2026', link:'https://sacregcf.academicworks.com/opportunities/1882', eligibility:['Architecture, engineering, or interior design major/course of study','High school senior or undergraduate planning to attend a 2-year or 4-year college/university','Minimum 2.5 unweighted GPA'], requirements:['General application','Career-goals essay','Reference letter'], essayPrompts:['Provide a personal statement on your educational and career goals in architecture, engineering, or interior design.'], tags:['architecture','engineering','stem','career','california'], minGrade:11, amount:'$2,500; renewable up to 3 years', amountMin:2500, amountMax:7500, previewCategory:'Architecture / Engineering Scholarship', sourceNotes:'Verified from official AcademicWorks page on 2026-05-07.' }),
  seed({ id:'aia-central-valley', name:'AIA Central Valley / John Ellis Architectural Scholarship', provider:'Sacramento Region Community Foundation', region:['Sacramento County','Placer County','Yolo County','El Dorado County','California'], deadline:'2026-03-13', deadlineLabel:'Verified 2026 deadline: March 13, 2026', link:'https://sacregcf.academicworks.com/opportunities/1937', eligibility:['High school senior, undergraduate, graduate, or adult re-entry student','Majoring in architecture','Minimum 3.5 GPA','Full-time enrollment'], requirements:['Architecture eligibility questions','Essay about life/family inspiration','Two recommendation letters'], essayPrompts:['What in your family or life story has influenced or inspired you to study architecture?'], tags:['architecture','design','career','placer','sacramento'], minGrade:12, amount:'$1,000', amountMin:1000, amountMax:1000, previewCategory:'Architecture Scholarship', sourceNotes:'Verified from official AcademicWorks page on 2026-05-07.' }),
  seed({ id:'dreier-family', name:'Dreier Family Scholarship', provider:'Sacramento Region Community Foundation', region:['Sacramento County'], deadline:'2026-03-13', deadlineLabel:'Verified 2026 deadline: March 13, 2026', link:'https://sacregcf.academicworks.com/opportunities/1932', eligibility:['High school senior or undergraduate currently attending school in Sacramento County','Planning to attend a 2-year college, vocational, trade, or technical school in Sacramento County','Minimum 2.5 cumulative GPA','Plan to work at least 10 hours/week while attending college'], requirements:['General application','Educational/career goals essay','One recommendation letter'], essayPrompts:['What are your educational and career goals, and where do you see yourself in 5-10 years?'], tags:['sacramento','career','trade','community college','need','work','foster youth'], minGrade:12, amount:'$1,000-$3,000', amountMin:1000, amountMax:3000, previewCategory:'Career / Trade Scholarship', sourceNotes:'Verified from official AcademicWorks page on 2026-05-07.' }),
  seed({ id:'benny-goodman', name:'Benny Goodman Foundation Scholarship', provider:'Sacramento Region Community Foundation', region:['California','Sacramento County','Placer County'], deadline:'2026-03-13', deadlineLabel:'Verified 2026 deadline: March 13, 2026', link:'https://sacregcf.academicworks.com/opportunities/1889', eligibility:['Attending any University of California or California State University in the fall','3.0 GPA in music classes','Majoring in music with emphasis in jazz or classical; preference for clarinet'], requirements:['Activity/work/performance list','Two recommendations, one from music director/instructor','Essay under 500 words'], essayPrompts:['How has music played a role in your life, and what are your future goals in music?'], tags:['music','arts','career','california','leadership'], minGrade:12, amount:'$1,000-$3,500', amountMin:1000, amountMax:3500, previewCategory:'Music Scholarship', sourceNotes:'Verified from official AcademicWorks page on 2026-05-07.' }),
  seed({ id:'david-breaux', name:'David Breaux Memorial Scholarship', provider:'Sacramento Region Community Foundation', region:['Yolo County','Sacramento County'], deadline:'2026-03-13', deadlineLabel:'Verified 2026 deadline: March 13, 2026', link:'https://sacregcf.academicworks.com/opportunities/1903', eligibility:['High school senior or undergraduate in first year of study','Attended or currently attending school in Yolo County','Minimum 3.0 GPA'], requirements:['General application','Essay on social justice and compassion','Two reference letters'], essayPrompts:['Describe your view on social justice and compassion and how it has or may play a role in your life.'], tags:['yolo','social justice','community service','leadership','need'], minGrade:11, amount:'$2,000; renewable up to 1 year', amountMin:2000, amountMax:4000, previewCategory:'Social Justice Scholarship', sourceNotes:'Verified from official AcademicWorks page on 2026-05-07.' }),
  seed({ id:'dillard-jackson', name:'Dillard-Jackson Family Scholarship', provider:'Sacramento Region Community Foundation', region:['Sacramento County'], deadline:'2026-03-13', deadlineLabel:'Verified 2026 deadline: March 13, 2026', link:'https://sacregcf.academicworks.com/opportunities/1935', eligibility:['Graduating senior from a high school in the Elk Grove school district','Planning to major in agriculture','Minimum 3.0 GPA','Full-time enrollment'], requirements:['General application','Agriculture goals essay','Reference letter from teacher or agriculture/community contact'], essayPrompts:['Why are you majoring in agriculture, and what are your career goals?'], tags:['sacramento','elk grove','agriculture','career','need'], minGrade:12, amount:'$1,000', amountMin:1000, amountMax:1000, previewCategory:'Agriculture Scholarship', sourceNotes:'Verified from official AcademicWorks page on 2026-05-07.' }),
  seed({ id:'sacramento-police-foundation', name:'Sacramento Police Foundation Scholarship', provider:'Sacramento Region Community Foundation', region:['Sacramento County'], deadline:'2026-05-01', deadlineLabel:'Verified 2026 deadline: May 1, 2026', link:'https://sacregcf.academicworks.com/opportunities/1955', eligibility:['High school senior enrolled in a Criminal Justice and Public Service Magnet Academy program','Plan to attend a 2-year or 4-year college/university or vocational/trade school','Minimum 2.5 unweighted GPA','Plan to complete 50 volunteer service hours by May 15, 2026'], requirements:['General application','Volunteer hours documentation or completion plan','Essay on career goals and Magnet Academy impact','Reference letter'], essayPrompts:['Address your educational/career goals and how the Magnet Academy impacted your decisions and growth.'], tags:['sacramento','public service','criminal justice','community service','career'], minGrade:12, amount:'$1,000', amountMin:1000, amountMax:1000, previewCategory:'Public Service Scholarship', sourceNotes:'Verified from official AcademicWorks page on 2026-05-07.' }),
  seed({ id:'nancy-reardan', name:'Nancy B. Reardan Scholarship Fund', provider:'Sacramento Region Community Foundation', region:['Sacramento County'], deadline:'2025-03-14', deadlineLabel:'Official page shows last verified deadline: March 14, 2025; annual cycle - verify before applying', link:'https://sacregcf.academicworks.com/opportunities/1721', eligibility:['Female high school senior attending a school in Sacramento County, or renewal student who attended Sacramento County high school','Plan to attend a two-year college, four-year college/university, vocational or trade school','Minimum 3.5 GPA','Preference for current or former foster youth'], requirements:['Personal essay','Eligibility questions','Two reference letters'], essayPrompts:['Describe your educational and career goals.'], tags:['sacramento','women','foster youth','need','leadership'], minGrade:12, amount:'$2,000-$4,000', amountMin:2000, amountMax:4000, previewCategory:'Women / Foster Youth Scholarship', sourceNotes:'Official page fetched 2026-05-07; deadline shown is 2025, so app labels it as annual/needs fresh verification before applying.' })
];

const TIER_B_SCHOLARSHIPS = [
  seed({ tier:'B', scope:'National', id:'coca-cola-scholars', name:'Coca-Cola Scholars Program Scholarship', provider:'Coca-Cola Scholars Foundation', educationLevel:'High school senior', amount:'$20,000', amountMin:20000, amountMax:20000, deadline:'2026-09-30', deadlineLabel:'Annual fall cycle - verify current deadline', link:'https://www.coca-colascholarsfoundation.org/apply/', eligibility:['Current high school senior in the United States','Planning to pursue a degree at an accredited U.S. post-secondary institution'], requirements:['Online application','Leadership, service, and school activity details'], essayPrompts:['Leadership and service short answers vary by cycle.'], tags:['national','leadership','community service','broad'] }),
  seed({ tier:'B', scope:'National', id:'jackie-robinson-foundation', name:'Jackie Robinson Foundation Scholarship', provider:'Jackie Robinson Foundation', educationLevel:'High school senior', amount:'Up to $35,000 over four years', amountMin:35000, amountMax:35000, deadline:'2026-01-10', deadlineLabel:'Annual winter cycle - verify current deadline', link:'https://jackierobinson.org/apply/', eligibility:['Graduating minority high school senior','U.S. citizen','Plan to attend an accredited four-year college or university'], requirements:['Online application','Essay questions','Recommendation','Financial information'], essayPrompts:['Leadership, community service, and barrier-overcoming prompts vary by cycle.'], tags:['national','leadership','community service','need','first-gen'] }),
  seed({ tier:'B', scope:'National', id:'horatio-alger-national', name:'Horatio Alger Association National Scholarship', provider:'Horatio Alger Association', educationLevel:'High school junior', amount:'Up to $25,000', amountMin:25000, amountMax:25000, deadline:'2026-03-15', deadlineLabel:'Annual March cycle - verify current deadline', link:'https://scholars.horatioalger.org/scholarships/', eligibility:['High school junior in the United States','Demonstrated critical financial need','Integrity and perseverance in overcoming adversity'], requirements:['Online application','Academic, activity, and financial information'], essayPrompts:['Adversity, goals, and perseverance prompts vary by program.'], tags:['national','need','adversity','leadership','broad'], minGrade:11 }),
  seed({ tier:'B', scope:'National', id:'gates-scholarship', name:'The Gates Scholarship', provider:'The Gates Scholarship', educationLevel:'High school senior', amount:'Last-dollar funding', amountMin:0, amountMax:0, deadline:'2026-09-15', deadlineLabel:'Annual late-summer/fall cycle - verify current deadline', link:'https://www.thegatesscholarship.org/scholarship', eligibility:['High school senior','Pell-eligible','U.S. citizen, national, or permanent resident','From at least one eligible minority group'], requirements:['Online application','Academic record','Leadership and personal information'], essayPrompts:['Leadership, goals, and background prompts vary by cycle.'], tags:['national','need','leadership','first-gen','broad'] }),
  seed({ tier:'B', scope:'National', id:'questbridge-college-prep', name:'QuestBridge College Prep Scholars Program', provider:'QuestBridge', educationLevel:'High school junior', amount:'Program benefits vary', amountMin:0, amountMax:0, deadline:'2026-03-20', deadlineLabel:'Annual spring cycle - verify current deadline', link:'https://www.questbridge.org/high-school-students/college-prep-scholars', eligibility:['High school junior','Strong academic record','Often serves students from low-income backgrounds'], requirements:['Online application','Academic and household information','Short answers/essays'], essayPrompts:['Personal background and college preparation prompts vary by cycle.'], tags:['national','need','first-gen','college prep','broad'], minGrade:11 }),
  seed({ tier:'B', scope:'National', id:'questbridge-national-college-match', name:'QuestBridge National College Match', provider:'QuestBridge', educationLevel:'High school senior', amount:'Full four-year scholarship at partner colleges', amountMin:0, amountMax:0, deadline:'2026-09-26', deadlineLabel:'Annual fall cycle - verify current deadline', link:'https://www.questbridge.org/high-school-students/national-college-match', eligibility:['High school senior','Strong academic record','Often serves students from low-income backgrounds'], requirements:['Online application','Essays','Recommendations','School report'], essayPrompts:['Personal, family, and college-match essays vary by cycle.'], tags:['national','need','first-gen','college prep','broad'] }),
  seed({ tier:'B', scope:'National', id:'burger-king-scholars', name:'Burger King Scholars Program', provider:'Burger King Foundation', educationLevel:'High school senior', amount:'Awards vary', amountMin:1000, amountMax:60000, deadline:'2026-12-15', deadlineLabel:'Annual fall/winter cycle - verify current deadline', link:'https://burgerking.scholarsapply.org/', eligibility:['High school senior in the United States, Canada, Puerto Rico, or Guam','Plan to enroll in post-secondary education'], requirements:['Online application','Work experience, activities, and grades'], essayPrompts:['Short responses vary by cycle.'], tags:['national','work','broad','leadership'] }),
  seed({ tier:'B', scope:'National', id:'ge-reagan-foundation', name:'GE-Reagan Foundation Scholarship Program', provider:'Ronald Reagan Presidential Foundation & Institute', educationLevel:'High school senior', amount:'Up to $40,000', amountMin:40000, amountMax:40000, deadline:'2026-01-05', deadlineLabel:'Annual winter cycle - verify current deadline', link:'https://www.reaganfoundation.org/education/scholarship-programs/ge-reagan-foundation-scholarship-program/', eligibility:['High school senior','U.S. citizen','Demonstrated leadership, drive, integrity, and citizenship'], requirements:['Online application','Recommendations','Academic and activity details'], essayPrompts:['Leadership and citizenship prompts vary by cycle.'], tags:['national','leadership','community service','broad'] }),
  seed({ tier:'B', scope:'National', id:'elks-mvs', name:'Most Valuable Student Scholarship', provider:'Elks National Foundation', educationLevel:'High school senior', amount:'Awards vary up to major national awards', amountMin:1000, amountMax:30000, deadline:'2026-11-12', deadlineLabel:'Annual fall cycle - verify current deadline', link:'https://www.elks.org/scholars/scholarships/mvs.cfm', eligibility:['High school senior','U.S. citizen'], requirements:['Online application','Leadership, scholarship, and financial need information'], essayPrompts:['Leadership and community prompts vary by cycle.'], tags:['national','leadership','need','community service','broad'] }),
  seed({ tier:'B', scope:'National', id:'prudential-emerging-visionaries', name:'Prudential Emerging Visionaries', provider:'Prudential and Ashoka', educationLevel:'Age-based youth program', amount:'Awards vary', amountMin:5000, amountMax:15000, deadline:'2026-11-01', deadlineLabel:'Annual fall cycle - verify current deadline', link:'https://www.prudential.com/links/about/emerging-visionaries', eligibility:['Young people with a project addressing a financial or societal challenge'], requirements:['Online application','Project description','Impact details'], essayPrompts:['Project, community impact, and vision prompts vary by cycle.'], tags:['national','leadership','community service','entrepreneurship','broad'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'davidson-fellows', name:'Davidson Fellows Scholarship', provider:'Davidson Institute', educationLevel:'Students 18 or younger', amount:'$10,000-$50,000', amountMin:10000, amountMax:50000, deadline:'2026-02-14', deadlineLabel:'Annual winter cycle - verify current deadline', link:'https://www.davidsongifted.org/gifted-programs/fellows-scholarship/', eligibility:['18 or younger','Completed a significant piece of work in an eligible category'], requirements:['Project submission','Nominators','Application materials'], essayPrompts:['Project significance and contribution prompts vary by category.'], tags:['national','stem','arts','research','broad'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'afa-teens-drive-smart', name:'Teen Driver Safety Scholarship/Contest Opportunities', provider:'AAA', educationLevel:'High school students', amount:'Awards vary', amountMin:1000, amountMax:15000, deadline:'2026-02-28', deadlineLabel:'Annual cycle - verify current deadline', link:'https://www.aaa.com/teendriversafety/', eligibility:['Teen students meeting current contest rules'], requirements:['Video or campaign submission','Contest entry materials'], essayPrompts:['Creative safety campaign instead of standard essay.'], tags:['national','no-essay','creative','broad'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'college-board-bigfuture', name:'BigFuture Scholarships', provider:'College Board', educationLevel:'High school students', amount:'Monthly drawings vary', amountMin:500, amountMax:40000, deadline:'2026-12-31', deadlineLabel:'Monthly/opportunity cycles - verify current rules', link:'https://bigfuture.collegeboard.org/pay-for-college/bigfuture-scholarships', eligibility:['Students who complete eligible college-planning steps'], requirements:['Complete BigFuture planning actions'], essayPrompts:['No traditional essay listed for many drawings.'], tags:['national','no-essay','college prep','broad'], minGrade:10 }),
  seed({ tier:'B', scope:'National', id:'niche-no-essay', name:'Niche No Essay Scholarship', provider:'Niche', educationLevel:'High school and college students', amount:'$25,000', amountMin:25000, amountMax:25000, deadline:'2026-12-31', deadlineLabel:'Recurring monthly cycle - verify current rules', link:'https://www.niche.com/colleges/scholarships/no-essay-scholarship/', eligibility:['U.S. students and families meeting current Niche rules'], requirements:['Profile/entry per official rules'], essayPrompts:['No essay.'], tags:['national','no-essay','broad'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'bold-org-no-essay', name:'Bold.org Public Scholarship Listings', provider:'Bold.org', educationLevel:'Students', amount:'Amount varies', amountMin:500, amountMax:25000, deadline:'2026-12-31', deadlineLabel:'Recurring cycles - verify current scholarship page', link:'https://bold.org/scholarships/', eligibility:['Eligibility varies by active Bold.org opportunity'], requirements:['Bold.org profile/entry per official rules'], essayPrompts:['Prompts vary by listing; some are no-essay.'], tags:['national','no-essay','broad'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'scholarships360-no-essay', name:'Scholarships360 Public Scholarship Listings', provider:'Scholarships360', educationLevel:'High school, college, and graduate students', amount:'Awards vary', amountMin:500, amountMax:10000, deadline:'2026-06-30', deadlineLabel:'Annual/recurring cycles - verify current rules', link:'https://scholarships360.org/scholarships/', eligibility:['Eligibility varies by public listing'], requirements:['Requirements vary by scholarship'], essayPrompts:['Prompts vary by scholarship.'], tags:['national','no-essay','broad'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'scholastic-art-writing', name:'Scholastic Art & Writing Awards', provider:'Alliance for Young Artists & Writers', educationLevel:'Grades 7-12', amount:'Awards vary', amountMin:500, amountMax:12500, deadline:'2026-12-01', deadlineLabel:'Regional deadlines vary - verify current deadline', link:'https://www.artandwriting.org/awards/how-to-enter/', eligibility:['Students in grades 7-12 meeting current category rules'], requirements:['Art or writing submission','Category-specific materials'], essayPrompts:['Creative submission; written artist statement may apply.'], tags:['national','arts','writing','creative'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'youngarts', name:'YoungArts Competition', provider:'National YoungArts Foundation', educationLevel:'Artists ages 15-18 or grades 10-12', amount:'Awards vary', amountMin:250, amountMax:10000, deadline:'2026-10-17', deadlineLabel:'Annual fall cycle - verify current deadline', link:'https://youngarts.org/apply/', eligibility:['Artists ages 15-18 or in grades 10-12','U.S. citizens, permanent residents, or legally able to receive taxable income in the U.S.'], requirements:['Discipline-specific portfolio/audition materials'], essayPrompts:['Artist and application prompts vary by discipline.'], tags:['national','arts','creative','music'], minGrade:10 }),
  seed({ tier:'B', scope:'National', id:'jfk-profile-courage', name:'Profile in Courage Essay Contest', provider:'John F. Kennedy Library Foundation', educationLevel:'High school students', amount:'Awards vary', amountMin:100, amountMax:10000, deadline:'2026-01-12', deadlineLabel:'Annual winter cycle - verify current deadline', link:'https://www.jfklibrary.org/learn/education/profile-in-courage-essay-contest', eligibility:['U.S. high school students meeting current contest rules'], requirements:['Essay submission','Citation requirements'], essayPrompts:['Write about an elected official who demonstrated political courage.'], tags:['national','writing','civic','history'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'vfw-voice-democracy', name:'Voice of Democracy Audio-Essay Contest', provider:'Veterans of Foreign Wars', educationLevel:'Grades 9-12', amount:'Awards vary', amountMin:1000, amountMax:35000, deadline:'2026-10-31', deadlineLabel:'Annual fall cycle - verify current deadline', link:'https://www.vfw.org/community/youth-and-education/youth-scholarships', eligibility:['Students in grades 9-12 meeting current VFW rules'], requirements:['Recorded essay','Entry form'], essayPrompts:['Annual patriotic theme changes each year.'], tags:['national','writing','civic','no-essay'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'patriot-pen', name:"Patriot's Pen Essay Contest", provider:'Veterans of Foreign Wars', educationLevel:'Grades 6-8', amount:'Awards vary', amountMin:500, amountMax:5000, deadline:'2026-10-31', deadlineLabel:'Annual fall cycle - verify current deadline', link:'https://www.vfw.org/community/youth-and-education/youth-scholarships', eligibility:['Middle school students meeting current VFW rules'], requirements:['Essay','Entry form'], essayPrompts:['Annual patriotic theme changes each year.'], tags:['national','writing','civic'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'equitable-excellence', name:'Equitable Excellence Scholarship', provider:'Equitable Foundation', educationLevel:'High school senior', amount:'Awards vary', amountMin:2500, amountMax:20000, deadline:'2026-12-18', deadlineLabel:'Annual winter cycle - verify current deadline', link:'https://equitable.com/foundation/equitable-excellence-scholarship', eligibility:['High school senior planning post-secondary education','Demonstrated courage, strength, and wisdom through community impact'], requirements:['Online application','Activity and impact details'], essayPrompts:['Community impact and future goals prompts vary by cycle.'], tags:['national','leadership','community service','broad'] }),
  seed({ tier:'B', scope:'National', id:'ron-brown-scholar', name:'Ron Brown Scholar Program', provider:'Ron Brown Scholar Program', educationLevel:'High school senior', amount:'$40,000', amountMin:40000, amountMax:40000, deadline:'2026-01-09', deadlineLabel:'Annual winter cycle - verify current deadline', link:'https://ronbrown.org/apply/ron-brown-scholarship/', eligibility:['Black/African American high school senior','U.S. citizen or permanent resident','Demonstrated academic achievement, leadership, and financial need'], requirements:['Application','Essays','Recommendations','Transcript'], essayPrompts:['Leadership, service, and personal goals prompts vary by cycle.'], tags:['national','leadership','need','community service','first-gen'] }),
  seed({ tier:'B', scope:'National', id:'hispanic-scholarship-fund', name:'Hispanic Scholarship Fund Scholar Program', provider:'Hispanic Scholarship Fund', educationLevel:'High school senior and college students', amount:'Awards vary', amountMin:500, amountMax:5000, deadline:'2026-02-15', deadlineLabel:'Annual winter cycle - verify current deadline', link:'https://www.hsf.net/scholarship', eligibility:['Of Hispanic heritage','U.S. citizen, permanent legal resident, or DACA','Minimum GPA requirements vary by level'], requirements:['Online application','FAFSA/state aid info if applicable','Recommendation may be requested'], essayPrompts:['Background, goals, and leadership prompts vary by cycle.'], tags:['national','need','first-gen','leadership','broad'] }),
  seed({ tier:'B', scope:'National', id:'api-a-scholars', name:'APIA Scholarship Program', provider:'APIA Scholars', educationLevel:'High school senior and college students', amount:'Awards vary', amountMin:2500, amountMax:20000, deadline:'2026-01-09', deadlineLabel:'Annual winter cycle - verify current deadline', link:'https://apiascholars.org/scholarship/apia-scholarship/', eligibility:['Asian and/or Pacific Islander ethnicity as defined by program','U.S. citizen, national, legal permanent resident, or qualifying status per rules','Minimum GPA and enrollment requirements'], requirements:['Online application','Essay responses','Recommendation may be requested'], essayPrompts:['Identity, leadership, and goals prompts vary by cycle.'], tags:['national','need','first-gen','leadership','broad'] }),
  seed({ tier:'B', scope:'National', id:'unigo-10k', name:'Unigo $10K Scholarship', provider:'Unigo', educationLevel:'Students 14+', amount:'$10,000', amountMin:10000, amountMax:10000, deadline:'2026-12-31', deadlineLabel:'Annual/recurring cycle - verify current rules', link:'https://www.unigo.com/scholarships/our-scholarships/unigo-10k-scholarship', eligibility:['Legal U.S. residents age 14 or older meeting current rules'], requirements:['Short written response','Entry form'], essayPrompts:['Short-answer prompt changes by cycle.'], tags:['national','writing','broad'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'supercollege', name:'SuperCollege Scholarship', provider:'SuperCollege', educationLevel:'High school, college, adult students', amount:'$1,000', amountMin:1000, amountMax:1000, deadline:'2026-12-31', deadlineLabel:'Recurring monthly cycle - verify current rules', link:'https://www.supercollege.com/scholarship/', eligibility:['Students and families meeting current official rules'], requirements:['Entry form'], essayPrompts:['No long essay listed in current common format.'], tags:['national','no-essay','broad'], minGrade:9 }),
  seed({ tier:'B', scope:'California', id:'cal-grant', name:'Cal Grant', provider:'California Student Aid Commission', educationLevel:'California students', amount:'State aid amount varies', amountMin:0, amountMax:0, deadline:'2026-03-02', deadlineLabel:'California priority deadline often March 2 - verify current deadline', link:'https://www.csac.ca.gov/cal-grants', eligibility:['California students meeting financial, GPA, residency, and program requirements'], requirements:['FAFSA or CADAA','GPA submission where required'], essayPrompts:['No scholarship essay; state aid application requirements apply.'], tags:['california','need','broad','state aid'], minGrade:12 }),
  seed({ tier:'B', scope:'California', id:'middle-class-scholarship', name:'Middle Class Scholarship', provider:'California Student Aid Commission', educationLevel:'California college students', amount:'State aid amount varies', amountMin:0, amountMax:0, deadline:'2026-03-02', deadlineLabel:'Linked to state aid timelines - verify current rules', link:'https://www.csac.ca.gov/middle-class-scholarship', eligibility:['California residents attending UC, CSU, or eligible CA institutions meeting program rules'], requirements:['FAFSA or CADAA','School eligibility and enrollment'], essayPrompts:['No scholarship essay; state aid application requirements apply.'], tags:['california','need','state aid','broad'], minGrade:12 }),
  seed({ tier:'B', scope:'California', id:'california-dream-act', name:'California Dream Act Application Aid Programs', provider:'California Student Aid Commission', educationLevel:'California students', amount:'State aid amount varies', amountMin:0, amountMax:0, deadline:'2026-03-02', deadlineLabel:'California priority deadline often March 2 - verify current deadline', link:'https://dream.csac.ca.gov/', eligibility:['Eligible California undocumented and nonresident students under current state rules'], requirements:['California Dream Act Application','School and residency information'], essayPrompts:['No scholarship essay; state aid application requirements apply.'], tags:['california','need','state aid','broad'], minGrade:12 }),
  seed({ tier:'B', scope:'California', id:'ca-community-colleges-promise', name:'California College Promise Grant', provider:'California Community Colleges / CCCApply', educationLevel:'Community college students', amount:'Enrollment fee waiver', amountMin:0, amountMax:0, deadline:'2026-12-31', deadlineLabel:'Deadlines vary by college - verify with campus', link:'https://www.cccapply.org/money/california-college-promise-grant', eligibility:['California community college students meeting financial need/residency rules'], requirements:['FAFSA, CADAA, or campus fee-waiver process'], essayPrompts:['No essay; financial aid/campus process applies.'], tags:['california','community college','need','trade','broad'], minGrade:12 }),
  seed({ tier:'B', scope:'California', id:'eop-csu', name:'CSU Educational Opportunity Program', provider:'California State University', educationLevel:'CSU applicants', amount:'Support program; aid varies', amountMin:0, amountMax:0, deadline:'2026-01-15', deadlineLabel:'CSU application/EOP deadlines vary - verify current campus deadlines', link:'https://www.calstate.edu/attend/student-services/eop', eligibility:['California residents or eligible students applying to CSU who meet EOP criteria'], requirements:['CSU application','EOP application materials','Recommendations may be required'], essayPrompts:['EOP background and support prompts vary by campus/cycle.'], tags:['california','first-gen','need','college prep','broad'], minGrade:12 }),
  seed({ tier:'B', scope:'National', id:'amazon-future-engineer', name:'Amazon Future Engineer Scholarship', provider:'Amazon Future Engineer', educationLevel:'High school senior', amount:'Up to $40,000', amountMin:40000, amountMax:40000, deadline:'2026-12-19', deadlineLabel:'Annual winter cycle - verify current deadline', link:'https://www.amazonfutureengineer.com/scholarships', eligibility:['High school senior planning computer science, engineering, or related field','Eligibility criteria vary by cycle'], requirements:['Online application','Academic and activity details'], essayPrompts:['Technology, goals, and impact prompts vary by cycle.'], tags:['national','stem','computer science','engineering','career'] }),
  seed({ tier:'B', scope:'National', id:'society-women-engineers', name:'SWE Scholarships', provider:'Society of Women Engineers', educationLevel:'Incoming and current college students', amount:'Awards vary', amountMin:1000, amountMax:20000, deadline:'2026-02-01', deadlineLabel:'Application windows vary by student type - verify current deadline', link:'https://swe.org/scholarships/', eligibility:['Students pursuing ABET-accredited engineering, engineering technology, or computer science programs','Eligibility varies by award'], requirements:['Online application','Transcript and recommendations may be required'], essayPrompts:['Engineering goals and background prompts vary by award.'], tags:['national','stem','engineering','women','career'], minGrade:12 }),
  seed({ tier:'B', scope:'National', id:'scholarships-for-women-stem', name:'BHW Women in STEM Scholarship', provider:'The BHW Group', educationLevel:'Undergraduate and graduate students', amount:'$3,000', amountMin:3000, amountMax:3000, deadline:'2026-04-15', deadlineLabel:'Annual spring cycle - verify current deadline', link:'https://thebhwgroup.com/scholarship', eligibility:["Women pursuing undergraduate or master's degrees in STEM fields"], requirements:['Essay','Application form'], essayPrompts:['STEM goals and technology prompt varies by cycle.'], tags:['national','stem','women','writing','career'], minGrade:12 }),
  seed({ tier:'B', scope:'National', id:'mensa-foundation', name:'Mensa Foundation Scholarship Program', provider:'Mensa Foundation', educationLevel:'U.S. students', amount:'Awards vary', amountMin:600, amountMax:2500, deadline:'2026-01-15', deadlineLabel:'Annual winter cycle - verify current deadline', link:'https://www.mensafoundation.org/what-we-do/scholarships/', eligibility:['U.S. students enrolled in a degree program for the following academic year'], requirements:['Essay','Application form'], essayPrompts:['Describe your career, academic, or vocational goals.'], tags:['national','writing','broad','career'], minGrade:12 }),
  seed({ tier:'B', scope:'National', id:'acs-scholars', name:'ACS Scholars Program', provider:'American Chemical Society', educationLevel:'High school senior and college students', amount:'Up to $5,000', amountMin:1000, amountMax:5000, deadline:'2026-03-01', deadlineLabel:'Annual spring cycle - verify current deadline', link:'https://www.acs.org/education/acs-scholars.html', eligibility:['Students from historically underrepresented groups in chemistry-related disciplines','Plan to pursue chemistry-related degree/career'], requirements:['Online application','Academic and financial information','Recommendations may be required'], essayPrompts:['Chemistry goals and background prompts vary by cycle.'], tags:['national','stem','chemistry','need','career'], minGrade:12 }),
  seed({ tier:'B', scope:'National', id:'tsa-scholarships', name:'Technology Student Association Scholarships', provider:'Technology Student Association', educationLevel:'TSA members', amount:'Awards vary', amountMin:500, amountMax:2500, deadline:'2026-04-01', deadlineLabel:'Annual cycle - verify current deadline', link:'https://tsaweb.org/', eligibility:['TSA members meeting specific award rules'], requirements:['Application materials vary by award'], essayPrompts:['STEM leadership and participation prompts vary.'], tags:['national','stem','leadership','career'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'create-a-greeting-card', name:'Create-A-Greeting-Card Scholarship Contest', provider:'Gallery Collection', educationLevel:'High school and college students', amount:'$10,000', amountMin:10000, amountMax:10000, deadline:'2026-03-03', deadlineLabel:'Annual spring cycle - verify current deadline', link:'https://www.gallerycollection.com/greeting-cards-scholarship.htm', eligibility:['High school, college, or university students meeting contest rules'], requirements:['Original greeting card design','Entry form'], essayPrompts:['Creative design submission instead of essay.'], tags:['national','arts','creative','no-essay'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'doodle-for-google', name:'Doodle for Google', provider:'Google', educationLevel:'K-12 students', amount:'Awards vary', amountMin:5000, amountMax:30000, deadline:'2026-03-14', deadlineLabel:'Annual cycle - verify current deadline', link:'https://doodles.google.com/d4g/', eligibility:['K-12 students meeting current contest rules'], requirements:['Doodle artwork','Artist statement','Entry form'], essayPrompts:['Artist statement tied to annual theme.'], tags:['national','arts','creative','no-essay'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'frame-my-future', name:'Frame My Future Scholarship Contest', provider:'Church Hill Classics', educationLevel:'High school senior and college students', amount:'Awards vary', amountMin:1000, amountMax:6000, deadline:'2026-04-01', deadlineLabel:'Annual spring cycle - verify current deadline', link:'https://www.diplomaframe.com/', eligibility:['Students planning to attend college and meeting current rules'], requirements:['Creative image submission','Statement'], essayPrompts:['Describe how your submission frames your future.'], tags:['national','arts','creative','writing'], minGrade:12 }),
  seed({ tier:'B', scope:'National', id:'project-yellow-light', name:'Project Yellow Light Scholarship Competition', provider:'Project Yellow Light', educationLevel:'High school and college students', amount:'Awards vary', amountMin:1000, amountMax:8000, deadline:'2026-03-01', deadlineLabel:'Annual spring cycle - verify current deadline', link:'https://projectyellowlight.com/', eligibility:['High school and college students meeting competition category rules'], requirements:['Video, billboard, or radio submission depending category'], essayPrompts:['Public safety creative campaign instead of standard essay.'], tags:['national','creative','no-essay','community service'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'national-merit', name:'National Merit Scholarship Program', provider:'National Merit Scholarship Corporation', educationLevel:'High school juniors/seniors', amount:'Awards vary', amountMin:2500, amountMax:2500, deadline:'2026-10-01', deadlineLabel:'PSAT/NMSQT entry timeline - verify current rules', link:'https://www.nationalmerit.org/s/1758/start.aspx?gid=2&pgid=61', eligibility:['Students who take PSAT/NMSQT and meet program requirements'], requirements:['PSAT/NMSQT participation','Program forms for finalists'], essayPrompts:['Finalist essay may apply.'], tags:['national','academic','broad'], minGrade:11 }),
  seed({ tier:'B', scope:'National', id:'rotary-local-club', name:'Rotary Club Scholarships', provider:'Rotary clubs', educationLevel:'High school seniors', amount:'Awards vary', amountMin:500, amountMax:5000, deadline:'2026-04-01', deadlineLabel:'Local club deadlines vary - verify your nearest club', link:'https://www.rotary.org/en/our-programs/scholarships', eligibility:['Eligibility varies by local Rotary club and district'], requirements:['Application materials vary by club','Service and leadership details often useful'], essayPrompts:['Service, leadership, and goals prompts vary.'], tags:['national','local','community service','leadership','broad'] }),
  seed({ tier:'B', scope:'National', id:'kiwanis-childrens-fund', name:"Kiwanis Children's Fund Scholarships", provider:"Kiwanis Children's Fund", educationLevel:'Key Club / Circle K members', amount:'Awards vary', amountMin:1000, amountMax:2500, deadline:'2026-02-01', deadlineLabel:'Annual cycle - verify current deadline', link:'https://www.kiwanis.org/scholarship-opportunities/', eligibility:['Key Club or Circle K members meeting award-specific rules'], requirements:['Application','Service and leadership details'], essayPrompts:['Service and leadership prompts vary by award.'], tags:['national','community service','leadership','broad'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'deca-scholarships', name:'DECA Scholarships', provider:'DECA Inc.', educationLevel:'DECA members', amount:'Awards vary', amountMin:1000, amountMax:5000, deadline:'2026-01-12', deadlineLabel:'Annual winter cycle - verify current deadline', link:'https://www.deca.org/scholarships', eligibility:['DECA members meeting award-specific rules'], requirements:['Online application','DECA participation and career interest details'], essayPrompts:['Business, leadership, and DECA participation prompts vary.'], tags:['national','business','leadership','career'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'ffa-scholarships', name:'FFA Scholarships', provider:'National FFA Organization', educationLevel:'FFA members and eligible students', amount:'Awards vary', amountMin:500, amountMax:10000, deadline:'2026-01-11', deadlineLabel:'Annual winter cycle - verify current deadline', link:'https://www.ffa.org/participate/grants-and-scholarships/scholarships/', eligibility:['Eligibility varies by FFA scholarship program'], requirements:['Application','Agriculture/career and activity details'], essayPrompts:['Agriculture, leadership, and career prompts vary.'], tags:['national','agriculture','career','leadership'], minGrade:12 }),
  seed({ tier:'B', scope:'National', id:'skillsusa-scholarships', name:'SkillsUSA Scholarships', provider:'SkillsUSA', educationLevel:'SkillsUSA members', amount:'Awards vary', amountMin:500, amountMax:5000, deadline:'2026-04-01', deadlineLabel:'Award deadlines vary - verify current deadline', link:'https://www.skillsusa.org/membership-resources/scholarships-financial-aid/', eligibility:['SkillsUSA members meeting award-specific rules'], requirements:['Application materials vary by scholarship'], essayPrompts:['Skilled trade, leadership, and career prompts vary.'], tags:['national','trade','career','leadership'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'mikeroweworks', name:'Work Ethic Scholarship Program', provider:'mikeroweWORKS Foundation', educationLevel:'Trade school / skilled trades students', amount:'Awards vary', amountMin:1000, amountMax:20000, deadline:'2026-04-17', deadlineLabel:'Annual spring cycle - verify current deadline', link:'https://mikeroweworks.org/scholarship/', eligibility:['Students pursuing approved skilled trade programs','Meet current program rules'], requirements:['Application','Work ethic materials','Program documentation'], essayPrompts:['Work ethic and career direction prompts vary.'], tags:['national','trade','career','work'], minGrade:12 }),
  seed({ tier:'B', scope:'National', id:'imagine-america', name:'Imagine America Scholarships', provider:'Imagine America Foundation', educationLevel:'Career school students', amount:'Awards vary', amountMin:1000, amountMax:1000, deadline:'2026-12-31', deadlineLabel:'School/program timing varies - verify current rules', link:'https://www.imagine-america.org/students/scholarships-education/', eligibility:['Students attending participating career colleges and meeting program rules'], requirements:['Application','Participating school/program details'], essayPrompts:['Career interest prompts may vary.'], tags:['national','trade','career','broad'], minGrade:12 }),
  seed({ tier:'B', scope:'National', id:'beauty-changes-lives', name:'Beauty Changes Lives Scholarships', provider:'Beauty Changes Lives Foundation', educationLevel:'Beauty and wellness students', amount:'Awards vary', amountMin:1000, amountMax:15000, deadline:'2026-12-31', deadlineLabel:'Multiple cycles - verify current opportunity deadlines', link:'https://beautychangeslives.org/scholarships/', eligibility:['Students pursuing beauty, wellness, or related programs; rules vary by award'], requirements:['Application','Creative or essay materials vary'], essayPrompts:['Career vision and beauty/wellness prompts vary by award.'], tags:['national','trade','career','creative'], minGrade:12 }),
  seed({ tier:'B', scope:'National', id:'nursing-org-scholarships', name:'Nursing.org Scholarships', provider:'Nursing.org', educationLevel:'Nursing students', amount:'Awards vary', amountMin:500, amountMax:5000, deadline:'2026-12-31', deadlineLabel:'Multiple listings - verify each scholarship', link:'https://www.nursing.org/scholarships/', eligibility:['Eligibility varies by nursing scholarship listing'], requirements:['Application requirements vary by award'], essayPrompts:['Nursing goals and service prompts vary.'], tags:['national','nursing','health','career'], minGrade:12 }),
  seed({ tier:'B', scope:'National', id:'tylenol-future-care', name:'Tylenol Future Care Scholarship', provider:'Tylenol', educationLevel:'Healthcare students', amount:'Awards vary', amountMin:5000, amountMax:10000, deadline:'2026-08-01', deadlineLabel:'Annual summer cycle - verify current deadline', link:'https://www.tylenol.com/news/scholarship', eligibility:['Students pursuing healthcare-related education and meeting current rules'], requirements:['Online application','Academic and career details'], essayPrompts:['Healthcare commitment and goals prompts vary by cycle.'], tags:['national','health','nursing','career'], minGrade:12 }),
  seed({ tier:'B', scope:'National', id:'healthcare-leaders', name:'Healthcare Scholarship Listings', provider:'Nurse.org', educationLevel:'Healthcare students', amount:'Awards vary', amountMin:500, amountMax:5000, deadline:'2026-01-29', deadlineLabel:'Annual/recurring cycles - verify each listing', link:'https://nurse.org/scholarships/', eligibility:['Students pursuing healthcare-related degrees; rules vary by listing'], requirements:['Requirements vary by scholarship'], essayPrompts:['Healthcare leadership or goals prompts vary by listing.'], tags:['national','health','nursing','writing','career'], minGrade:12 }),
  seed({ tier:'B', scope:'National', id:'live-mas', name:'Live Mas Scholarship', provider:'Taco Bell Foundation', educationLevel:'Students ages 16-26', amount:'Awards vary', amountMin:5000, amountMax:25000, deadline:'2026-01-03', deadlineLabel:'Annual winter cycle - verify current deadline', link:'https://www.tacobellfoundation.org/live-mas-scholarship/', eligibility:['Students ages 16-26 meeting current rules','Passion-driven application'], requirements:['Video application','Application form'], essayPrompts:['Video response about passion and plans.'], tags:['national','creative','career','broad'], minGrade:10 }),
  seed({ tier:'B', scope:'National', id:'tallo-scholarships', name:'Tallo Scholarships', provider:'Tallo', educationLevel:'Students', amount:'Awards vary', amountMin:500, amountMax:15000, deadline:'2026-12-31', deadlineLabel:'Multiple recurring opportunities - verify each listing', link:'https://tallo.com/scholarships/', eligibility:['Eligibility varies by Tallo opportunity'], requirements:['Profile/entry requirements vary'], essayPrompts:['Prompts vary by opportunity.'], tags:['national','broad','career','no-essay'], minGrade:9 }),
  seed({ tier:'B', scope:'National', id:'going-merry-scholarships', name:'Going Merry Scholarship Listings', provider:'Going Merry', educationLevel:'Students', amount:'Awards vary', amountMin:500, amountMax:25000, deadline:'2026-12-31', deadlineLabel:'Database listings vary - verify each source', link:'https://www.goingmerry.com/scholarships/', eligibility:['Eligibility varies by listed scholarship'], requirements:['Application requirements vary by scholarship'], essayPrompts:['Prompts vary by scholarship.'], tags:['national','broad','database'], minGrade:9 })
];

const SCHOLARSHIP_SEEDS = [...TIER_A_SCHOLARSHIPS, ...TIER_B_SCHOLARSHIPS];

const PACKET_TEMPLATES = {
  fullPacket: ['Fit rationale', 'Essay starter', 'Timeline', 'Requirements', 'Submission checklist', 'Official link verification'],
  applicationChecklist: ['Verify deadline on official page', 'Create account only on official scholarship site', 'Draft essays in a separate doc', 'Request recommendation', 'Review for accuracy', 'Submit before deadline', 'Save confirmation'],
  recommendationRequest: ['Ask 3-4 weeks before deadline', 'Give recommender resume + prompt + deadline', 'Share 2-3 traits to emphasize', 'Send polite reminder 7 days before due date'],
  faq: ['Free Sacramento / Placer beta', 'No account needed for free packet', 'Paid tier is waitlist-only', 'No award guarantees', 'Submit applications only through official scholarship portals']
};

const SAMPLE_STUDENT = { studentName:'Maya Alvarez', parentEmail:'maya.parent@example.test', studentAge:'17', grade:'12', gpa:'3.5-3.9', county:'Sacramento County', zip:'95819', school:'East Sacramento High School', activities:'Saturday food bank volunteer, founder of a peer tutoring circle, part-time barista, first chair clarinet, and senior class service chair', priorityThemes:'service, first-gen, local', majorCareer:'public health with a long-term goal of working in community clinics' };

function normalizeText(value) { return String(value || '').trim(); }
function splitTags(value) { return normalizeText(value).toLowerCase().split(/[,;\n]+|\s+and\s+/).map(s => s.trim()).filter(Boolean); }
function gradeNumber(grade) { const g = normalizeText(grade).toLowerCase(); if (g.includes('gap') || g.includes('recent graduate') || g.includes('12') || g.includes('senior')) return 12; if (g.includes('11') || g.includes('junior')) return 11; if (g.includes('10')) return 10; if (g.includes('9')) return 9; return 11; }
function isExpiredLowQuality(scholarship, today = TODAY) { const deadline = new Date(`${scholarship.deadline}T23:59:59-07:00`); const keepForPlanning = /annual|verify|varies|recurring|monthly|cycle|verified 2026/i.test(scholarship.deadlineLabel || ''); return scholarship.quality === 'low' || (!keepForPlanning && deadline < today); }
function regionScore(student, scholarship) { const loc = `${student.county || ''} ${student.zip || ''} ${student.location || ''}`.toLowerCase(); if (scholarship.tier === 'A' && scholarship.region.some(r => loc.includes(r.toLowerCase().replace(' county','')))) return 8; if (scholarship.scope === 'California' || scholarship.region.includes('California')) return 3; if (scholarship.scope === 'National') return 1; return 0; }
function scoreScholarship(student, scholarship) {
  if (isExpiredLowQuality(scholarship) || gradeNumber(student.grade) < (scholarship.minGrade || 9)) return -999;
  const studentTags = [...splitTags(student.activities), ...splitTags(student.interests), ...splitTags(student.priorityThemes), ...splitTags(student.majorCareer), ...splitTags(student.qualifiers), normalizeText(student.county).toLowerCase().replace(' county','')];
  let score = regionScore(student, scholarship) + (scholarship.tier === 'A' ? 12 : 0);
  for (const tag of scholarship.tags) if (studentTags.some(t => tag.includes(t) || t.includes(tag))) score += scholarship.tier === 'A' ? 4 : 2;
  if (/service|volunteer|community|tutor|food bank/i.test(student.activities || '') && scholarship.tags.includes('community service')) score += 5;
  if (/leader|captain|president|mentor|chair|founder/i.test(student.activities || '') && scholarship.tags.includes('leadership')) score += 4;
  if (/engineer|construction|transport|stem|computer|architecture|health|public|nursing|business|media|music|agriculture|justice|trade|weld|hvac|electric|cosmetology/i.test(student.majorCareer || '') && scholarship.tags.some(t => ['engineering','architecture','stem','career','media','music','agriculture','public service','criminal justice','health','nursing','trade','computer science'].includes(t))) score += 4;
  if (/first.gen|first generation/i.test(student.qualifiers || student.priorityThemes || '') && scholarship.tags.includes('first-gen')) score += 3;
  if (/need|aid/i.test(student.qualifiers || '') && scholarship.tags.includes('need')) score += 2;
  return score;
}
function discoverScholarships(student, seeds = SCHOLARSHIP_SEEDS) {
  const ranked = seeds.map(s => ({ ...s, fitScore: scoreScholarship(student, s) })).filter(s => s.fitScore > -999).sort((a,b) => b.fitScore - a.fitScore || (a.tier === 'A' ? -1 : 1) || a.name.localeCompare(b.name));
  const tierA = ranked.filter(s => s.tier === 'A');
  return { best: tierA[0] || ranked[0] || null, lightMatches: tierA.slice(1, 3), additionalMatches: tierA.slice(3), lockedMatches: [], totalFound: ranked.length, ranked, tierACount: tierA.length, tierBCount: ranked.filter(s => s.tier === 'B').length };
}
function listStudentSignals(student) {
  const signals = [];
  const activities = normalizeText(student.activities);
  const career = normalizeText(student.majorCareer);
  if (activities) signals.push(`your ${activities.split(',')[0].trim()} experience`);
  if (/tutor|mentor|teach/i.test(activities)) signals.push('the tutoring or mentoring work you can describe with specifics');
  if (/job|work|barista|cashier|caregiv|family/i.test(activities)) signals.push('the responsibility you carry outside school');
  if (/president|chair|captain|leader|founder/i.test(activities)) signals.push('a leadership role with visible follow-through');
  if (career) signals.push(`your ${career} goal`);
  return [...new Set(signals)].slice(0, 4);
}
function buildFitRationale(student, scholarship) {
  const name = normalizeText(student.studentName) || 'This student';
  const reasons = [];
  const signals = listStudentSignals(student);
  if (scholarship.tier === 'A' && regionScore(student, scholarship) >= 8) reasons.push(`${name} has a real local tie through ${normalizeText(student.county) || 'the Sacramento/Placer area'}`);
  if (/service|volunteer|community|tutor|food bank/i.test(student.activities || '') && scholarship.tags.includes('community service')) reasons.push(`the application can point to ${signals.find(s => /volunteer|tutor|food bank|experience|work/i.test(s)) || 'specific service work'} instead of generic language`);
  if (/leader|captain|president|mentor|chair|founder/i.test(student.activities || '') && scholarship.tags.includes('leadership')) reasons.push('there is a concrete leadership example to use in essays and recommendation requests');
  if (signals.length && reasons.length < 3) reasons.push(`the profile already has usable details: ${signals.join('; ')}`);
  if (scholarship.tier === 'B') reasons.push('this is a broader database lead, so verify fit and current rules before investing application time');
  return reasons.length ? `This is a strong first target because ${reasons.join(', ')}.` : `This is a practical target because ${name}'s profile has clear material for a specific application.`;
}
function makeEssayOutline(student) {
  const name = normalizeText(student.studentName) || 'the student';
  const activities = normalizeText(student.activities) || 'one meaningful class, job, family responsibility, club, sport, or volunteer activity';
  const firstActivity = activities.split(',')[0].trim();
  const goal = normalizeText(student.majorCareer) || 'your next education/career step';
  const local = normalizeText(student.county) || 'your local community';
  return [`Opening story: Start with one real scene from ${firstActivity} - what was happening, who needed help, and what ${name} did next.`, `What it shows: Connect that moment to reliability, service, leadership, or persistence without overstating it.`, `Student-specific bridge: Tie the story to ${goal}.`, `Local angle: Mention how studying or living in ${local} shaped the way ${name} thinks about community and opportunity.`, 'Close: Name the practical barrier the scholarship would reduce and the next step the student is ready to take.'];
}
function makeEssayStarter(student, scholarship) { const name = normalizeText(student.studentName) || 'the student'; const activity = (normalizeText(student.activities) || 'one regular responsibility').split(',')[0].trim(); const goal = normalizeText(student.majorCareer) || "the student's college and career goal"; const county = normalizeText(student.county) || "the student's community"; const prompt = scholarship.essayPrompts?.[0] || 'Tell us about your goals and experiences.'; return `Start with a specific moment from ${activity}, not a broad statement about wanting a scholarship. For this prompt - "${prompt}" - the strongest opening is a short scene that shows ${name}'s follow-through, then a bridge to ${goal} and why ${county} shaped that goal. Keep it honest and concrete: one scene, one lesson, one next step.`; }
function deadlineUrgency(scholarship, today = TODAY) { const deadline = new Date(`${scholarship.deadline}T23:59:59-07:00`); if (!Number.isNaN(deadline.getTime()) && deadline >= today && /verified 2026/i.test(scholarship.deadlineLabel || '')) { const days = Math.max(0, Math.round((deadline - today) / 86400000)); return days === 0 ? 'Deadline today - verify immediately' : `Deadline in ${days} day${days === 1 ? '' : 's'} - verify on the official page`; } return scholarship.deadlineLabel || 'Deadline varies - verify on official page'; }
function realnessSignal(scholarship) { const tags = scholarship.tags.join(' '); if (scholarship.tier === 'B') return 'Wider database lead: confirm current eligibility, deadline, and official application page before applying.'; if (/community service|volunteer/i.test(tags)) return 'Strong applications use specific service hours, named impact, and a recommender who can confirm follow-through.'; if (/leadership/i.test(tags)) return 'Strong applications point to real responsibility, not just a title.'; if (/stem|engineering|architecture|career|media|music|agriculture/i.test(tags)) return "Strong applications connect the student's course, job, project, or activity to a clear career direction."; return 'Strong applications use clear goals, honest details, complete documents, and verified official deadlines.'; }
function valueRange(matches) {
  const usable = matches.filter(m => Number(m.amountMax) > 0);
  return usable.reduce((acc, m) => ({ min: acc.min + (Number(m.amountMin) || Number(m.amountMax) || 0), max: acc.max + (Number(m.amountMax) || Number(m.amountMin) || 0) }), { min:0, max:0 });
}
function money(n) { return Number(n || 0).toLocaleString('en-US', { style:'currency', currency:'USD', maximumFractionDigits:0 }); }
function toVisibleMatch(report, m, idx) {
  return { scholarshipId:m.id, id:m.id, tier:m.tier, scope:m.scope, name:m.name, provider:m.provider, educationLevel:m.educationLevel, amount:m.amount || m.awardRange || 'Amount varies', amountMin:m.amountMin, amountMax:m.amountMax, awardRange:m.amount || m.awardRange || 'Amount varies', deadline:m.deadlineLabel, deadlineUrgency:deadlineUrgency(m), status:m.status, realnessSignal:realnessSignal(m), link:m.link, sourceNotes:m.sourceNotes, fitRationale:buildFitRationale(report.student,m), requirements:m.requirements, eligibility:m.eligibility, essayPrompts:m.essayPrompts, tags:m.tags, description: m.tier === 'A' ? `${m.previewCategory}. Prepared as a guided local match with official-source notes and application steps.` : `${m.scope} wider-database opportunity. Use it to explore, then verify the official page before applying.`, priority:idx === 0 ? 'Best Match' : (m.tier === 'A' ? 'Strong Local Match' : 'Browse Lead') };
}
function allVisibleMatches(report) { return report.discovery.ranked.map((m, idx) => toVisibleMatch(report, m, idx)); }
function generateReport(student) {
  const normalizedStudent = { ...student, parentEmail: normalizeText(student.parentEmail || student.email).toLowerCase() };
  const discovery = discoverScholarships(normalizedStudent);
  if (!discovery.best) return { student: normalizedStudent, account:createAccountSession(normalizedStudent), discovery, fullPacket: null, lightMatches: [], additionalMatches: [], allMatches: [], topMatches: [], browseMatches: [], unlocked: true, freeBeta: FREE_BETA, disclaimer: disclaimer(), estimatedValue:{ min:0, max:0, label:'$0' } };
  const s = discovery.best;
  const fullPacket = { ...toVisibleMatch({ student: normalizedStudent, discovery }, s, 0), overview: `${s.name} is a verified local/core opportunity in this beta. Use the official link to confirm the portal status before applying.`, eligibilityChecklist: s.eligibility.map(x => ({ item: x, status: 'Verify / prepare' })), requiredDocuments: s.requirements, essayPromptBreakdown: s.essayPrompts.map(prompt => ({ prompt, approach: 'Answer with one specific story, one proof point, and one clear education/career goal.' })), starterDraftOutline: makeEssayOutline(normalizedStudent), essayStarter: makeEssayStarter(normalizedStudent, s), recommendationGuidance: PACKET_TEMPLATES.recommendationRequest, applicationInstructions: ['Open the official scholarship link only', 'Verify the portal status and eligibility', 'Draft essays in a separate document', 'Collect documents', 'Ask recommender early', 'Submit before the official deadline if the current cycle is open', 'Save confirmation'], submissionChecklist: PACKET_TEMPLATES.applicationChecklist, timeline: ['Tonight: verify official page and save deadline/status', 'Next 48 hours: collect transcript/resume/activity list', 'This week: draft essay and request recommendation', '7 days before due date: final review', '2 days before due date: submit and save confirmation'] };
  const report = { student: normalizedStudent, account: createAccountSession(normalizedStudent), discovery, unlocked: true, freeBeta: FREE_BETA, fullPacket, lightMatches: [], additionalMatches: [], allMatches: [], topMatches: [], browseMatches: [], templates: PACKET_TEMPLATES, disclaimer: disclaimer(), generatedAt: new Date().toISOString() };
  report.allMatches = allVisibleMatches(report);
  report.topMatches = report.allMatches.filter(m => m.tier === 'A').slice(0, 8);
  report.lightMatches = report.topMatches.slice(1, 3);
  report.additionalMatches = report.topMatches.slice(3);
  report.browseMatches = report.allMatches;
  report.unlockedCount = report.allMatches.length;
  const est = valueRange(report.allMatches);
  report.estimatedValue = { ...est, label: `${money(est.min)} - ${money(est.max)}` };
  return report;
}
function createAccountSession(student) { const email = normalizeText(student.parentEmail || student.email).toLowerCase(); return { email, accountId: email ? `acct_${hashString(email)}` : `acct_demo_${Date.now()}`, sessionId: `sess_${hashString(`${email}|${Date.now()}`)}`, dashboardPath: '#dashboard', mode: 'free_beta_local_access' }; }
function hashString(value) { let h = 0; for (const ch of String(value)) h = Math.imul(31, h) + ch.charCodeAt(0) | 0; return Math.abs(h).toString(36); }
function scheduleEmailQueue(report, now = new Date()) { const email = report.student.parentEmail; const base = now.getTime(); const mk = (delayHours, subject, purpose, body) => ({ id: `${report.account.accountId}_${delayHours}h`, to: email, subject, purpose, scheduledAt: new Date(base + delayHours*3600*1000).toISOString(), status: 'queued_placeholder_not_sent', body }); return [mk(0, 'Your free scholarship starter pack is ready', 'instant_dashboard_ready', `Hi ${report.student.studentName || 'there'} - your free local beta Starter Pack is ready. Start with the Best Match, then review the remaining verified-source matches. No awards are guaranteed; verify each official deadline before applying.`), mk(24, 'Reminder: verify your top scholarship deadline', '24h_deadline_verification', 'Quick reminder: before drafting, open the official scholarship page and confirm the current portal status, deadline, and eligibility.'), mk(48, 'Next step: choose one essay to draft first', '48h_application_momentum', 'Pick the strongest fit, draft one specific story, and ask a recommender early if the official application requires one.')]; }
function queueAccessAndFollowupEmails(report, storage = null) { const queue = scheduleEmailQueue(report); if (storage?.setItem) storage.setItem('ssp_email_queue', JSON.stringify(queue)); return queue; }
function unlockFullPlan(report) { return { ...report, unlocked: true, unlockedCount: report.discovery.totalFound, unlockedAt: new Date().toISOString(), unlockedOpportunities: allVisibleMatches(report).slice(3) }; }
function createUpgradeIntent(planId, contactEmail='') { return { planId, planName: 'Paid tier waitlist', price: '$0 today', contactEmail, status: 'paid_tier_waitlist_only_no_payment', paymentLink: '', message: 'Paid tier is launching soon. No payment is requested or processed in this beta.', createdAt: new Date().toISOString() }; }
function disclaimer() { return 'Actual awards depend on application strength and award decisions. We help you apply well; we do not decide who wins. Always verify deadlines and eligibility on the official scholarship page before applying.'; }
function logAnalyticsEvent(eventName, details = {}, storage = null, now = new Date()) { const allowed = new Set(['intake_completed','report_viewed','dashboard_viewed','print_clicked','beta_refine_clicked','upgrade_clicked','unlock_triggered','status_changed','award_added','waitlist_joined','browse_filter_changed']); if (!allowed.has(eventName)) throw new Error(`Unknown analytics event: ${eventName}`); const store = storage || (typeof localStorage !== 'undefined' ? localStorage : null); let events = []; if (store?.getItem) { try { events = JSON.parse(store.getItem('ssp_analytics_events') || '[]'); } catch { events = []; } } const event = { eventName, details, at: now.toISOString() }; events.push(event); if (store?.setItem) store.setItem('ssp_analytics_events', JSON.stringify(events)); return event; }
function makeDashboardModel(report, storedStatuses = {}) {
  const visible = report.allMatches || [];
  const items = visible.map((item, idx) => ({ ...item, id:item.scholarshipId || item.id, status: storedStatuses[item.scholarshipId]?.status || 'Not started', priority: item.priority || (idx === 0 ? 'Best Match' : idx < 3 ? 'Strong Match' : 'Additional Match'), nextAction: item.tier === 'A' ? 'Open the full plan, confirm current-cycle status, then draft the first essay from the starter.' : 'Verify the official listing before spending application time.', documents: idx === 0 ? report.fullPacket.requiredDocuments : (Array.isArray(item.requirements) ? item.requirements : String(item.requirements || '').split('; ').filter(Boolean)), checklist: ['Open official page', 'Confirm current cycle/deadline', 'Confirm eligibility', 'Collect documents', 'Draft/update essay', 'Request recommendation if needed', 'Submit only on official site', 'Save confirmation'].map(label => ({ label, done: storedStatuses[item.scholarshipId]?.checklist?.includes(label) || false })) }));
  const topMatches = items.filter(i => i.tier === 'A');
  return { items, topMatches, browseMatches: items, totalFound: report.discovery.totalFound, unlockedCount: items.length, estimatedValue: report.estimatedValue || valueRange(items), progressPercent: topMatches.length ? Math.round(topMatches.flatMap(i=>i.checklist).filter(c=>c.done).length / (topMatches.length*8) * 100) : 0 };
}
function filterBrowseMatches(matches, filter) {
  if (!filter || filter === 'All') return matches;
  const f = filter.toLowerCase();
  if (f.includes('local')) return matches.filter(m => m.scope === 'Local Sacramento + Placer' || (m.region || []).some(r => /sacramento|placer/i.test(r)));
  if (f.includes('california')) return matches.filter(m => m.scope === 'California' || (m.region || []).includes('California'));
  if (f.includes('national')) return matches.filter(m => m.scope === 'National');
  if (f.includes('no-essay')) return matches.filter(m => (m.tags || []).includes('no-essay'));
  if (f.includes('major')) return matches.filter(m => (m.tags || []).some(t => /stem|engineering|health|nursing|trade|career|music|arts|business|agriculture|computer|architecture/i.test(t)));
  return matches;
}
function saveLocal(key, value) { if (typeof localStorage !== 'undefined') localStorage.setItem(key, JSON.stringify(value)); return value; }
function loadLocal(key, fallback=null) { if (typeof localStorage === 'undefined') return fallback; try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }

const ScholarshipStarter = { SCHOLARSHIP_SEEDS, TIER_A_SCHOLARSHIPS, TIER_B_SCHOLARSHIPS, STATUS_OPTIONS, PACKET_TEMPLATES, SAMPLE_STUDENT, FREE_BETA, discoverScholarships, generateReport, makeDashboardModel, createUpgradeIntent, createAccountSession, scheduleEmailQueue, queueAccessAndFollowupEmails, unlockFullPlan, logAnalyticsEvent, saveLocal, loadLocal, disclaimer, isExpiredLowQuality, scoreScholarship, deadlineUrgency, realnessSignal, filterBrowseMatches };
if (typeof window !== 'undefined') window.ScholarshipStarter = ScholarshipStarter;
export { SCHOLARSHIP_SEEDS, TIER_A_SCHOLARSHIPS, TIER_B_SCHOLARSHIPS, STATUS_OPTIONS, PACKET_TEMPLATES, SAMPLE_STUDENT, FREE_BETA, discoverScholarships, generateReport, makeDashboardModel, createUpgradeIntent, createAccountSession, scheduleEmailQueue, queueAccessAndFollowupEmails, unlockFullPlan, logAnalyticsEvent, deadlineUrgency, realnessSignal, disclaimer, scoreScholarship, isExpiredLowQuality, filterBrowseMatches };
